language: objective-c
osx_image: xcode7.3
before_install:
  - xctool -v
  - brew install protobuf
install:
  - scripts/build.sh
  - scripts/makeTests.sh
script: xctool -project ./src/runtime/ProtocolBuffers.xcodeproj -sdk iphonesimulator -scheme ProtocolBuffers build test
